version: '3'

services:
  {{ cookiecutter.docker_service_name }}:
    container_name: {{ cookiecutter.container_name }}
    build:
      context: .
      dockerfile: Dockerfile      
    environment:
      WORKERS_PER_CORE: "0.125"     #https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi
      LOG_LEVEL: "debug"      # debug|info|warning|error|critical      
      IS_DEBUG: false
      API_KEY: {{ cookiecutter.api_key }}
      DEFAULT_MODEL_PATH: /app/ai_model/model-best/
      APPLICATION_INSIGHTS_KEY: {{ cookiecutter.application_insights_key }}
    ports:
      - "{{ cookiecutter.port }}:80"    
    volumes:
      - ./model-best/model-best:/app/ai_model/model-best
    